# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20170831_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarryXP',
            fields=[
                ('xp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stats.XP')),
                ('lumpNotPool', models.BooleanField()),
            ],
            bases=('stats.xp',),
        ),
    ]
