# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 03:07
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20170921_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedition',
            name='log',
            field=markdownx.models.MarkdownxField(default=1),
            preserve_default=False,
        ),
    ]
